### ISSUE TITLE
Option to anonymize IP address ranges before storage 

### ISSUE THREAD

**Issue by macinjosh32** [geoip-lite/node-geoip#202]
From our understanding of GDPR and CCPA, businesses/controllers aren't allowed to persist IP addresses of users who are protected under such laws unless those IP addresses are first anonymized, i.e. zeroing out the last octet of IPv4 addresses and last 80 bits of IPv6 addresses. Since it's impossible to determine whether everyone with a given IP address has consented to non-anonymized storage at DB download time, it seems the only safe option would be anonymize all IP addresses before storage.

Would it be possible to add an option to the GeoIP DB update script to store IP address ranges in anonymized form?

Out of curiosity, I ran some GeoIP DB queries on a bunch of anonymized IP addresses, and the results were identical to the non-anonymized versions. I'm not sure whether lookups for certain edge cases would fail, though.

**Comment by ar2rsawseen** [comment]
So GeoIP lite actually stored ranges yes. The specific range may differ per case, so hard to say how much would be affected in total.

I've actually run into a similar issue, but in my case, we receive connection, determine its IP, and get the location. Then we simply discard IP addresses without storing them at all. So it is compliant.

But we had a client sending pre anonymized IP addresses and it seemed to work quite well. In some cases city was different, but in most cases the Country was correct.

**Comment by macinjosh32** [comment]
If the last octet (IPv4) / last 80 bits (IPv6) doesn't matter for any of the stored ranges -- e.g. all IPv4 storage ranges begin with *.*.*.0 and end with *.*.*.255 -- then there's no problem. I could look at the MaxMind files and check.

In our case, we also use anonymized IP address and discard them without storing. I'm more concerned because the geoip-lite updater seems to be fetching and persisting the IP address ranges locally without checking whether any of the ranges are split down the last octet. If they were, wouldn't that potentially violate GDPR/CCPA (for non-consenting users in EU/CA) to the same extent as if our application were to persist full IP addresses directly?

**Comment by bluesmoon** [comment]
The IP in the geoip database didn't come from a user and isn't tied to a
web request. If this were a problem, then it would be illegal to store most
numbers between 0 and 4.2 billion in any form. Elementary schools would be
violating the law for teaching arithmetic.

**Comment by ar2rsawseen** [comment]
I see, but in that sense IP ranges are anonymous, so it would not violate compliance any more than having a txt file of all possible IP addresses generated stored on your server. It is you as a data processor, who would tie them together with some information, like location, etc. So it would be your responsibility to anonymized data. But from GeoIP lite side, it should be all ok :)

**Comment by macinjosh32** [comment]
@bluesmoon Those are good points, particularly regarding how the GeoIP ranges can't be mapped to requests.  The only remaining issue I's been wondering about was whether we would be required to remove a given IP address from all storage if a user issued a "Do Not Sell" request. I would have thought such requests irrelevant since we don't sell that data, but I got thrown off a bit by https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ indicating that MaxMind would even need to remove such an IP address from its free/public database (not just its paid one) if it received such a request. But thinking it over, this kind of makes sense from a business standpoint since it could lead to the free DB being more comprehensive than the paid one.

@ar2rsawseen I understand that geoip-lite itself only plays a data processing role, but I wasn't sure whether from a legal standpoint an application's Node.js modules would be considered as part of / inseparable from our application, even though we didn't write the geoip-lite code. But you're right -- it doesn't really matter either way.

**Comment by macinjosh32** [comment]
Per @ar2rsawseen and @bluesmoon 's points, I'm convinced there isn't a compelling use case for this option yet. If you guys agree, feel free to close this feature request.

**Comment by ar2rsawseen** [comment]
The bottom line, if you are not sure, then Maxmind is keeping their data in compliance and removing records per request. 
So updating data periodically would make sure you are following their compliance too :)
