### ISSUE TITLE
longitude and latitude is not the real possion!

### ISSUE THREAD

**Issue by AmerAnsari** [geoip-lite/node-geoip#203]
When I trying to get longitude and latitude via IP address, longitude and latitude is not exactly the real position that I want

**Comment by bluesmoon** [comment]
It's the longitude and latitude of the ISP's endpoint. What were you hoping
for?

>

**Comment by AmerAnsari** [comment]
> It's the longitude and latitude of the ISP's endpoint. What were you hoping for?
> […](#)

I want to get user longitude and latitude from the user device IP address, but my receive result is not a real device longitude and latitude!!

**Comment by bluesmoon** [comment]
IPs are not specific to users. The same IP can be assigned to different
users at different times since it's allocated via DHCP. The only thing that
doesn't change is the ISP. If you want the user's location, then use the
device GPS. You'll need to get user permission for this via a browser
prompt.

**Comment by AmerAnsari** [comment]
> IPs are not specific to users. The same IP can be assigned to different users at different times since it's allocated via DHCP. The only thing that doesn't change is the ISP. If you want the user's location, then use the device GPS. You'll need to get user permission for this via a browser prompt.

Thanks for your help dude!

**Comment by bluesmoon** [comment]
Documentation is here: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
