### ISSUE TITLE
Prototype pollution from async and lodash

### ISSUE THREAD

**Issue by jfoclpf** [geoip-lite/node-geoip#204]
We have installed snyk on our npm package `autocosts` and snyk is reporting for some weeks a security vulnerability on behalf of `geoip-lite@1.4.2`

```
Detailed paths
Introduced through: autocosts@jfoclpf/autocosts#fe2c8b8ce19ad42afba866887180461c51bab964 › geoip-lite@1.4.2 › async@2.6.3 › lodash@4.17.15
Remediation: Open PR to patch lodash@4.17.15.
Introduced through: autocosts@jfoclpf/autocosts#fe2c8b8ce19ad42afba866887180461c51bab964 › geoip-lite@1.4.2 › ip-address@5.9.4 › lodash@4.17.15
Remediation: Open PR to patch lodash@4.17.15.
```

![image](https://user-images.githubusercontent.com/3984909/83135701-84410f80-a0e6-11ea-9166-93f1a718922c.png)

I'm not sure if async already remedied this issue but just to let you know that your package is triggering this security vulnerability

**Comment by bluesmoon** [comment]
Fixed in async 2.6.3, so we should be good.
