### ISSUE TITLE
Download data programmatically

### ISSUE THREAD

**Issue by bartbutenaers** [geoip-lite/node-geoip#205]
Hi Philip (@bluesmoon),

Thanks for sharing this useful module!

I would like to download the files programmatically, before calling ```geoip.reloadDataSync()```?
I mean something like this:
 ```
geoip.downloadDataAsync("YOUR_LICENSE_KEY", function() {
   // Files have been download when arriving in this callback handler.
   // So let's reload those files now ...
   geoip.reloadDataSync();
})
```
Do you think this is possible?  
And do you have any tips on how I could achieve something like that?

Kind regards,
Bart Butenaers

**Comment by bluesmoon** [comment]
I think that's exactly what the update script does.

**Comment by bartbutenaers** [comment]
Ok thanks!
So I need to call the updatedb.js script from my code:
```
var child = exec("node /home/pi/.node-red/node_modules/geoip-lite/scripts license_key=MY_LICENSE_KEY", function (error, stdout, stderr) {
   geoip.reloadDataSync();
});
```
Then the files are indeed downloaded:

![image](https://user-images.githubusercontent.com/14224149/83955869-04d6dd00-a858-11ea-8821-56f57611ae9b.png)

But I never arrive in the callback function for some reason... 
Which means I have to call the ```geoip.reloadDataSync();``` explicit afterwards.

Would you perhaps call the script file in another way?

**Comment by bartbutenaers** [comment]
Hi Philip (@bluesmoon),

I solved it by using this code:
```
var exec = require('child_process').exec;
var command = "node ./node_modules/geoip-lite/scripts/updatedb.js license_key=MY_LICENSE_KEY";
var updateProcess = require('child_process').exec(command);
node.updateProcess.stdout.on('data', function(data) {
   if (data.includes("Failed to Update Databases from MaxMind")) {
      // Here is my code to handle the failure
    }
                    
   if (data.includes('Successfully Updated Databases from MaxMind')) {
       // As soon as the data have been downloaded, it can be loaded.
       geoip.reloadDataSync();
   }
});
```
Not really 100% failure proof, in case you ever change your logging texts ...
But at the moment it seems to be working fine, so I will close this issue.

**Comment by bluesmoon** [comment]
i'm not really sure why you need this.  You can use the `startWatchingDataUpdate` function that will do the reload for you when the data files update.

**Comment by bluesmoon** [comment]
This is documented in the README at https://github.com/geoip-lite/node-geoip#ways-to-reload-data-in-your-app-when-update-finished

**Comment by bartbutenaers** [comment]
Ok thanks!!  That looks interesting also.  Seem I have not seen that option for some reason ...
