### ISSUE TITLE
Issue with country

### ISSUE THREAD

**Issue by mhterres** [geoip-lite/node-geoip#209]
I started to notice a few days ago that the country returned cometimes is incorrect.

If I check the IP on the MaxMind GeoIP2 Demo website (https://www.maxmind.com/en/geoip-demo) it is correct, but the npm package returns a different country.

Example:
Website
149.71.88.117 GB

My code:

const geoip=require('geoip-lite')
const geo = geoip.lookup('149.71.88.117')
console.log(geo.country)

node test.js 
HR

Is there some kind of issues with the DB being used by the package?

**Comment by bluesmoon** [comment]
Have you updated your DB recently? MaxMind releases a new database every month, and their website uses the commercial version of the database. If your database is older than a month, or if it is the free version, then it may not have the same results as their website.
