### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by dumaixx** [geoip-lite/node-geoip#213]
I have been installed package and types for it. Trying to use it in code, but browser drops me error like 
![Screenshot from 2020-10-02 13-35-24](https://user-images.githubusercontent.com/50488110/94914726-3c772e00-04b4-11eb-96c3-34e160b25a6c.png)
Whats wrong?

**Comment by bluesmoon** [comment]
Not sure what you mean by "browser drops an error". This package is not meant to be run in a browser, it runs on the server in node.js.

**Comment by dumaixx** [comment]
@bluesmoon Yea, I run it in backend and dont know why error occures. Try to install previous version 1.4.0 like types is, but doesnt help

**Comment by dumaixx** [comment]
My bad. Running it in front part of project ...
