### ISSUE TITLE
Update script is fetching new data from maxmind everytime I push it on Heroku.

### ISSUE THREAD

**Issue by GauravMirchandani** [geoip-lite/node-geoip#214]
Hello, as mentioned the Package stores checksums of MaxMind data and by default only downloads them if checksums have changed and this worked fine but since around 1 month I am facing issue, every time I push my code to heroku, the script fetches new data every time and starts updating. This consumes a lot of time. I tend to push the updates daily or twice in a day. And I am using this script:
npm run-script updatedb license_key=YOUR_LICENSE_KEY

**Comment by bluesmoon** [comment]
Can you paste the console output when you run the command?

**Comment by GauravMirchandani** [comment]
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 4 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 1.68 KiB | 574.00 KiB/s, done.
Total 15 (delta 13), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  12.16.1
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 12.16.1...
remote:        Downloading and installing node 12.16.1...
remote:        Using default npm version: 6.13.4
remote:
remote: -----> Restoring cache
remote:        - node_modules
remote:
remote: -----> Installing dependencies
remote:        Installing node modules
remote:
remote:        > sq-native@0.8.0 install
/tmp/build_be3e2f0e/node_modules/sq-native
remote:        > node-pre-gyp install
remote:
remote:        [sq-native] Success:
"/tmp/build_be3e2f0e/node_modules/sq-native/bindings/napi-v3/libsqreen.node"
is installed via remote
remote:
remote:        > nodemon@2.0.4 postinstall
/tmp/build_be3e2f0e/node_modules/nodemon
remote:        > node bin/postinstall || exit 0
remote:
remote:        Love nodemon? You can now support the project via the open
collective:
remote:         > https://opencollective.com/nodemon/donate
remote:
remote:
remote:        > nodemailer@6.4.10 postinstall
/tmp/build_be3e2f0e/node_modules/nodemailer
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:
remote:                                   === Nodemailer 6.4.10 ===
remote:
remote:        Thank you for using Nodemailer for your email sending needs!
While Nodemailer
remote:        itself is mostly meant to be a SMTP client there are other
related projects in
remote:        the Nodemailer project as well.
remote:
remote:        > IMAP API (  https://imapapi.com  ) is a server application
to easily access
remote:          IMAP accounts via REST API
remote:        > ImapFlow (  https://imapflow.com/  ) is an async IMAP
client
library for
remote:          Node.js
remote:        > NodemailerApp (  https://nodemailer.com/app/  ) is a cross
platform GUI app to
remote:          debug emails
remote:        > Project Pending (  https://projectpending.com/  ) allows
you
to host DNS of
remote:          your project domains
remote:        > Pending DNS (  https://pendingdns.com/  ) is the DNS
server used that powers
remote:          Project Pending
remote:        > Ethereal Email (  https://ethereal.email/  ) is an email
testing service that
remote:          accepts all your test emails
remote:
remote:        ........
remote:
remote:        > ejs@3.0.1 postinstall /tmp/build_be3e2f0e/node_modules/ejs
remote:        > node ./postinstall.js
remote:
remote:
remote:        > thehobbytribe@1.0.0 postinstall /tmp/build_be3e2f0e
remote:        > cd node_modules/geoip-lite && npm run-script updatedb
license_key=$GEOIP
remote:
remote:
remote:        > geoip-lite@1.4.2 updatedb
/tmp/build_be3e2f0e/node_modules/geoip-lite
remote:        > node scripts/updatedb.js "license_key=GbwCgZjLpQZjYjYo"
remote:
remote:        Checking  GeoLite2-Country-CSV.zip
remote:        Database country has new data
remote:        Fetching  GeoLite2-Country-CSV.zip
remote:        Retrieving GeoLite2-Country-CSV.zip ... DONE
remote:        Extracting GeoLite2-Country-CSV.zip ... DONE
remote:        Processing Lookup Data (may take a moment) ... DONE
remote:        Processing Data (may take a moment) ...
remote:        Still working (41884) ...
remote:        Still working (88969) ...
remote:        Still working (137518) ...
remote:        Still working (184166) ...
remote:        Still working (230627) ...
remote:        Still working (278521) ... DONE
remote:        Processing Data (may take a moment) ...
remote:        Still working (34352) ...
remote:        Still working (71387) ... DONE
remote:        Checking  GeoLite2-City-CSV.zip
remote:        Database city has new data
remote:        Fetching  GeoLite2-City-CSV.zip
remote:        Retrieving GeoLite2-City-CSV.zip ... DONE
remote:        Extracting GeoLite2-City-CSV.zip ... DONE
remote:        Processing Data (may take a moment) ...
remote:        Still working (47364) ...
remote:        Still working (92686) ...
remote:        Still working (138779) ...
remote:        Still working (184636) ...
remote:        Still working (229758) ...
remote:        Still working (275075) ...
remote:        Still working (320586) ...
remote:        Still working (365478) ...
remote:        Still working (410787) ...
remote:        Still working (456099) ...
remote:        Still working (501724) ...
remote:        Still working (545727) ...
remote:        Still working (591240) ...
remote:        Still working (636067) ...
remote:        Still working (681927) ...
remote:        Still working (727088) ...
remote:        Still working (772236) ...
remote:        Still working (817538) ...
remote:        Still working (863166) ...
remote:        Still working (908644) ...
remote:        Still working (954161) ...
remote:        Still working (999788) ...
remote:        Still working (1045298) ...
remote:        Still working (1090862) ...
remote:        Still working (1135765) ...
remote:        Still working (1180722) ...
remote:        Still working (1226293) ...
remote:        Still working (1271865) ...
remote:        Still working (1317192) ...
remote:        Still working (1362323) ...
remote:        Still working (1408142) ...
remote:        Still working (1453387) ...
remote:        Still working (1498717) ...
remote:        Still working (1544397) ...
remote:        Still working (1589140) ...
remote:        Still working (1634479) ...
remote:        Still working (1680011) ...
remote:        Still working (1724993) ...
remote:        Still working (1770844) ...
remote:        Still working (1816424) ...
remote:        Still working (1861203) ...
remote:        Still working (1906721) ...
remote:        Still working (1952606) ...
remote:        Still working (1997448) ...
remote:        Still working (2042830) ...
remote:        Still working (2088527) ...
remote:        Still working (2133889) ...
remote:        Still working (2179475) ...
remote:        Still working (2225005) ...
remote:        Still working (2269914) ...
remote:        Still working (2315204) ...
remote:        Still working (2360741) ...
remote:        Still working (2406173) ...
remote:        Still working (2449054) ...
remote:        Still working (2494769) ...
remote:        Still working (2540030) ...
remote:        Still working (2585578) ...
remote:        Still working (2631138) ...
remote:        Still working (2676740) ...
remote:        Still working (2722517) ...
remote:        Still working (2767561) ...
remote:        Still working (2812539) ...
remote:        Still working (2856648) ...
remote:        Still working (2902323) ...
remote:        Still working (2947390) ...
remote:        Still working (2992688) ...
remote:        Still working (3038289) ...
remote:        Still working (3083539) ...
remote:        Still working (3129029) ...
remote:        Still working (3174665) ...
remote:        Still working (3220260) ...
remote:        Still working (3265925) ...city data processed
remote:        Processing Data (may take a moment) ...
remote:        Still working (34021) ...
remote:        Still working (68942) ...
remote:        Still working (104207) ...
remote:        Still working (138851) ...
remote:        Still working (173604) ...
remote:        Still working (208801) ...
remote:        Still working (243865) ...
remote:        Still working (278529) ...
remote:        Still working (313683) ...
remote:        Still working (348817) ... DONE
remote:        Successfully Updated Databases from MaxMind.
remote:        added 411 packages in 489.57s
remote:
remote: -----> Build
remote:
remote: -----> Caching build
remote:        - node_modules
remote:
remote: -----> Pruning devDependencies
remote:        audited 412 packages in 3.074s
remote:
remote:        10 packages are looking for funding
remote:          run `npm fund` for details
remote:
remote:        found 3 low severity vulnerabilities
remote:          run `npm audit fix` to fix them, or `npm audit` for details
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 97.2M
remote: -----> Launching...

**Comment by GauravMirchandani** [comment]
I pushed again after 5 mins
See it started to update again 😞

> geoip-lite@1.4.2 updatedb /tmp/build_4cb253ae/node_modules/geoip-lite
remote:        > node scripts/updatedb.js "license_key=GbwCgZjLpQZjYjYo"
remote:
remote:        Checking  GeoLite2-Country-CSV.zip
remote:        Database country has new data
remote:        Fetching  GeoLite2-Country-CSV.zip
remote:        Retrieving GeoLite2-Country-CSV.zip ... DONE
remote:        Extracting GeoLite2-Country-CSV.zip ... DONE
remote:        Processing Lookup Data (may take a moment) ... DONE
remote:        Processing Data (may take a moment) ...
remote:        Still working (37646) ...
remote:        Still working (78745) ...
remote:        Still working (123439) ...
remote:        Still working (165457) ...
remote:        Still working (204847) ...
remote:        Still working (247315) ...
remote:        Still working (290572) ... DONE

**Comment by GauravMirchandani** [comment]
It keeps on updating every time I push, kindly help.

**Comment by bluesmoon** [comment]
Looks like you might be overwriting the previous installation every time you push, so there is no previous data.

**Comment by GauravMirchandani** [comment]
Any solution to this?

**Comment by bluesmoon** [comment]
I don't know how Heroku apps work, but if you do a fresh installation every time, then that's what you need to change. It's not an issue with this package. Every package you install is doing the same thing, this one is just visible because it has a lot of data to pull.
