### ISSUE TITLE
Cannot read property 'country' of null

### ISSUE THREAD

**Issue by the-prodigy** [geoip-lite/node-geoip#216]
When I just try to implement the middleware on this website [](https://adonisjs.com/docs/4.1/middleware#_creating_middleware)

I always get an error:

`Cannot read property 'country' of null`

Even I execute this in my middleware I get NULL:

```
const ip = request.ip()
request.country = await geoip.lookup(ip)
```

**Comment by corollari** [comment]
There's no need to await the result since it's synchronous. I'm also not sure why you are setting `request.country` to the result of a lookup, could you explain a little bit more what you are trying to achieve?
