### ISSUE TITLE
need to update the maxmind urls for getting new data

### ISSUE THREAD

**Issue by steevhise** [geoip-lite/node-geoip#218]
in the update script the URLs for updating the data appear to be out of date.

this is where to get the new ones:
`https://www.maxmind.com/en/accounts/<account number>/geoip/downloads`

**Comment by ar2rsawseen** [comment]
Hello,
as far as I tried current links, like:

https://geoip.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&suffix=zip&license_key=LICENSE_KEY

are working for me, any problems that you experience?

**Comment by steevhise** [comment]
strange, earlier today when i ran the the update script, via `npm run updatedb license_key=<my key>` npm was giving me a connection error / host not found message. however, it seems to be working now. maybe temporary net glitch...?
