### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by TeodorKolev** [geoip-lite/node-geoip#221]
Question: Can I use this library for a commercial purposes, or I need any permissions from the owner of this library **or** **MaxMind**?
Thank you in advance

**Comment by ar2rsawseen** [comment]
Hello,
all you need to know is here:
https://github.com/geoip-lite/node-geoip/blob/master/LICENSE

But basically yes, you can use it for commercial purposes, with proper attribution to Maxmind (basically when referencing features you use there, you should mention that is provided by Maxmind)

**Comment by TeodorKolev** [comment]
Hello @ar2rsawseen 

Thanks for your reply. Can can I attribute to Maxmind?

Thanks again

**Comment by ar2rsawseen** [comment]
Yeah, as per Maxmind license:
https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en#license

They even show example on how to attribute.

**Comment by TeodorKolev** [comment]
Thank you once again.
Should I include this in html or I can add it in header and now show this to users? My application is Angular.

Thanks once again

**Comment by ar2rsawseen** [comment]
Afaik you don't have to use it on every page, but only in the places where you mentioned the functionality of determining countly/city/etc based on IP address, you need to mention it is provided by MaxMind. Like documentation and promotional materials

**Comment by bluesmoon** [comment]
Note that we are not representatives of MaxMind, so don't take this as legal advice. If you're unclear, it would be best to contact MaxMind directly.
