### ISSUE TITLE
[Question] Is there any recommended way to convert region to full name?

### ISSUE THREAD

**Issue by indeyets** [geoip-lite/node-geoip#224]
Short identifiers of country and region are useful as identifiers for database. I use them a lot. But, sometimes, I need to present data to end-users.

There are a lot of packages to convert country-codes to country names (and it's easy to do it "in house" by referencing official ISO list of codes).

Is there any standard for region names? Or is my only option to fall-back to some other geoip package which would fetch this from geoip database?

**Comment by indeyets** [comment]
ping @ar2rsawseen, @bluesmoon

**Comment by bluesmoon** [comment]
I just use MaxMind's CSV files to convert from region code to Region Names.

**Comment by bluesmoon** [comment]
Apparently this is recommended by MaxMind's PHP binding: http://www.geonames.org/

**Comment by bluesmoon** [comment]
This might be useful for JavaScript: https://www.npmjs.com/package/iso-3166-2
