### ISSUE TITLE
Handle GeoIP database failures

### ISSUE THREAD

**Issue by nitinwason1983** [geoip-lite/node-geoip#225]
We should block the docker build if the GeoIP database can't be updated. Currently it is passing even if we don't provide the correct licence key.

https://github.com/geoip-lite/node-geoip/blob/master/scripts/updatedb.js#L174

https://github.com/geoip-lite/node-geoip/blob/master/scripts/updatedb.js#L627 (Missing license key)

It should return non-zero exit code in the case where the license key is bad (which leads to a 400 response instead of 200 in code above).

Please suggest.

**Comment by ar2rsawseen** [comment]
Hello,
so you can update those process.exit calls (there are multiple there are multiple there I think) and if it fits your needs, we would gladly accept a PR :)

**Comment by bluesmoon** [comment]
I believe several people have asked us to allow the build to proceed even on failure as they would like to run the update separately.
