### ISSUE TITLE
Database load in memory per process even if belongs to the same app?

### ISSUE THREAD

**Issue by SorinGFS** [geoip-lite/node-geoip#227]
From readme file:
> Quick test on memory consumption shows that library uses around 100Mb **per process**

Suppose I start an app with PM2 with 10 processes, do I get the MaxMind db loaded in memory 10 times?

If so, can't this be solved somehow?

**Comment by bluesmoon** [comment]
I don't know what PM2 is, but the way to do it is to start one process,
load the library, and then fork 10 children. All children will inherit the
same in-memory copy of the db since Linux uses copy on write, and we never
write to it after load.

**Comment by SorinGFS** [comment]
> I don't know what PM2 is, but the way to do it is to start one process, load the library, and then fork 10 children. All children will inherit the same in-memory copy of the db since Linux uses copy on write, and we never write to it after load.

Ok, thank you for explanation.
