### ISSUE TITLE
Library unusable due to "colors" module debacle

### ISSUE THREAD

**Issue by CherryDT** [geoip-lite/node-geoip#231]
![image](https://user-images.githubusercontent.com/6010463/148789743-c8ffb25a-4c88-4e51-9562-98fa03ea527d.png)

This is because the `colors` library is allowed to be updated to 1.4.1/1.4.2, introducing [this mess](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/).

Pinning it to `1.4.0` should fix it for now. Consider switching to an alternative.

**Comment by bluesmoon** [comment]
New version pushed
