### ISSUE TITLE
Re: Database updates

### ISSUE THREAD

**Issue by kreationnext** [geoip-lite/node-geoip#241]
I sometimes forget to update the db files so can you do something like the data files are updated prior to compilation.

This is an important feature that you can add if possible. This will be an important feature.

I really love your work. And can you tell me when you are going to release the next update?

**Comment by bluesmoon** [comment]
Maxmind license does not allow us to distribute the latest version of the library along with the package. Only the user of the library is allowed to download it.

**Comment by kreationnext** [comment]
I didn't mean to distribute the list, what I meant was like a cron kind of stuff that would download the database say every week if license key is assigned. Can you do that.

**Comment by bluesmoon** [comment]
Yes, many people do that. It's not something that can be built into the library since it's an operating system level configuration.

**Comment by kreationnext** [comment]
Like for example
if(updatedb ever receives license key) {
store license key in a file
}

setInterval(() => {
run updatedb with the stored license key
}, every 7 days);

**Comment by kreationnext** [comment]
this can be this way too

```
lookup(ip) {
	...
	download_data();
}
updatedb(LICENSE_KEY) {
	...
	save_license_key_to_file();
}
download_data() {
	var last_data_download_date = load_date_from_file_stored_or_memory();
	var last_week = new Date();
	var mutex = is_singlerun();
	last_week.setDate(last_week.getDate() - 7);
	if(last_data_download_date > last_week) {
		var license_key = load_from_stored_license_key_file();
		if(mutex && license_key != "") {
			updatedb_async(license_key);
			reload_data();
			update_last_data_download_date_to_file_and_memory();
		}
	}
}
```

**Comment by kreationnext** [comment]
what do you think?

**Comment by kreationnext** [comment]
Thank you for your response.

Then I have only one option is ask a favor from you.

The issue is one of my client think you and MaxMind are in the same. They don't allow me to update the database unless you release an update. Though this is an odd request but still can you just change only the version number monthly so that I can convince them that they need to update the database.

**Comment by kreationnext** [comment]
After you released the last update on 25th April, I updated the database on May. There after I am unable to convince him that an update is required. I have done several rebuilds thereafter but cannot convince him that a database update is required. As such my only option was to reach out to you.

**Comment by bluesmoon** [comment]
Can't you set up a cron job on the host? BTW, in my experience automated
updates are not a good idea. We've found many times that an update broke
things because maxmind changed something. Always need to run tests after an
update.

**Comment by bluesmoon** [comment]
I also don't have the time to do monthly updates. I haven't even used this
library in almost 10 years since our codebase moved to Java.

**Comment by kreationnext** [comment]
The issue is I cannot edit the code. The code was written by my client's son. After his demise he keeps it as his memory. I am only allowed to do a rebuild and update the database when you give a new release.

**Comment by kreationnext** [comment]
> Can't you set up a cron job on the host? BTW, in my experience automated updates are not a good idea. We've found many times that an update broke things because maxmind changed something. Always need to run tests after an update.

He hosts it on his local system. So I can't do any changes without him noticing. I don't take money from him. I want to help him survive through his old days. He has been by my side in my worst days, so trying to give him some comfort and also preserve his sentiments.

**Comment by kreationnext** [comment]
We do a lot of things for ourselves, a small charity like this wouldn't hurt I think.

**Comment by kreationnext** [comment]
I think I will have to write a similar library then, since you don't have time

**Comment by bluesmoon** [comment]
I plan to release a new version this coming week. Please ping me if not done by Wednesday.
