### ISSUE TITLE
Sometimes geoip return null value 

### ISSUE THREAD

**Issue by Mdsarowarhossain** [geoip-lite/node-geoip#243]
![Screenshot_20220922-082733](https://user-images.githubusercontent.com/98280301/191645000-0ea2eade-5e6d-4d82-8d36-e0b398b0ed61.jpg)
Hello  am use geoip-lite in my nodejs project. But some time geoip-lite return null value

**Comment by bluesmoon** [comment]
that means there was no mapping. Look up the IP on the MaxMind website, and make sure you have an up-to-date GeoIP database.

**Comment by Mdsarowarhossain** [comment]
> that means there was no mapping. Look up the IP on the MaxMind website, and make sure you have an up-to-date GeoIP database.

Am use it in nodejs. Geoip-lite npm package. My check with my WiFi network am see geoip return null value

**Comment by bluesmoon** [comment]
Have you verified with the MaxMind website? Every time you find an IP mapping to null, your first check should be to enter that IP on the website at https://www.maxmind.com/en/geoip-demo and see what it gives you.

* If it's null on the website, that means there's no mapping
* If it is not-null on the website, that means your local geoip database is outdated (remember that you have to update your database monthly)
* If your database is up-to-date, then it's possible that you have the free database and the mapping is only available in the commercial database (MaxMind provides different levels of accuracy for the two databases)
