### ISSUE TITLE
401 Unauthorized when trying to upgrade

### ISSUE THREAD

**Issue by ollydixon** [geoip-lite/node-geoip#246]
We have a paid account at https://www.maxmind.com

We have a license key there.

<img width="563" alt="Screenshot 2022-11-11 at 09 51 08" src="https://user-images.githubusercontent.com/6940726/201302723-283d9230-5053-4e46-993f-4d089a1cfa8d.png">

Get the following error.

<img width="750" alt="Screenshot 2022-11-11 at 09 53 00" src="https://user-images.githubusercontent.com/6940726/201303100-b7910ca5-619b-4c8e-8e22-d7cdcfa16703.png">

```Checking  GeoLite2-Country-CSV.zip```
```ERROR: HTTP Request Failed [401 Unauthorized]```

**Comment by ollydixon** [comment]
The documentation is wrong.

The following works.

```node ./node_modules/geoip-lite/scripts/updatedb.js license_key=XYZ```

**Comment by bluesmoon** [comment]
@ollydixon not sure how your command is different from running `npm run updatedb license_key=XYZ` as internally npm does exactly what you've written.

**Comment by bluesmoon** [comment]
hmm, I wonder if the quoting is an issue

**Comment by bluesmoon** [comment]
no, doesn't look like that's an issue. Are you sure the license key is the same in both commands?

**Comment by bluesmoon** [comment]
Both commands call the same url:
```
bos-mp9bf:node-geoip ptellis$ npm run updatedb license_key=ABC123

> geoip-lite@1.4.6 updatedb
> node scripts/updatedb.js "license_key=ABC123"

https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&suffix=zip&license_key=ABC123
Checking  GeoLite2-Country-CSV.zip
ERROR: HTTP Request Failed [401 Unauthorized]
bos-mp9bf:node-geoip ptellis$ node scripts/updatedb.js license_key=ABC123
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&suffix=zip&license_key=ABC123
Checking  GeoLite2-Country-CSV.zip
ERROR: HTTP Request Failed [401 Unauthorized]
```

**Comment by ollydixon** [comment]
@bluesmoon I don't know I just copied the command and run in the project root both times.

**Comment by bluesmoon** [comment]
ok.  That error message is very specific to an invalid license key. Might help to edit the source and add some logging statements to see if there are any differences in the requests.

**Comment by ollydixon** [comment]
@bluesmoon I'll close for now.
