### ISSUE TITLE
Get the postal / zip code ? 

### ISSUE THREAD

**Issue by MustaphaHAMADI** [geoip-lite/node-geoip#250]
Is there any way to get the postal code or the zip code from this package ?

**Comment by bluesmoon** [comment]
It's not possible at the moment. You would need to patch the code to add that info to our data structure

**Comment by sapics** [comment]
I have created [ip-location-api](https://github.com/sapics/ip-location-api) which has similar in-memory database system with `geoip-lite`.
You can display "zip code" whose field name is `postcode` as following

```bash
# Update database
npm run updatedb ILA_FIELDS=country,region1,city,metro,eu,timezone,latitude,area,postcode

# application running
node your_application.js ILA_FIELDS=country,region1,city,metro,eu,timezone,latitude,area,postcode
```
