### ISSUE TITLE
The included data is out of date

### ISSUE THREAD

**Issue by jessethomson** [geoip-lite/node-geoip#251]
The data included in the most recent version of `geoip-lite` is over 3 years old (from 2019-08-28).

I know that users of this npm package can manually update the data themselves, but I think it would be great to update the data that is included by default.

Thoughts?

My understanding is that this would be fairly straightforward, and just require running `npm run updatedb`, verifying that the tests pass, and then committing the result.

I'm happy to create a pull request with this update if the maintainer(s) are open to it. It's also fine if you'd rather make the change yourself, so let me know!

Related: https://github.com/geoip-lite/node-geoip/pull/183 (<-- Previous update)

**Comment by jessethomson** [comment]
Separate, but related: It would probably be pretty easy to set up a Github Action that runs once a month (or some other cadence) that runs the updatedb script and then creates a pull request with the result.

I'd also be open to helping out with that if that's something others are interested in

**Comment by bluesmoon** [comment]
We are not legally permitted to include the latest version of the database with this library. The version distributed with the library is the last version allowed by the MaxMind license.
