### ISSUE TITLE
IP from US but the returned result is from Africa

### ISSUE THREAD

**Issue by linhnguyeneverfit** [geoip-lite/node-geoip#253]
I was trying to use the IP address `199.188.237.46` (US) to lookup the country name and got the result is in a country from Africa. Pls help me to take a look it. Many thanks

<img width="923" alt="Screen Shot 2023-04-06 at 09 36 42" src="https://user-images.githubusercontent.com/104880745/230258297-60c328ab-84e7-4fa3-94e5-10ceddec2676.png">
<img width="353" alt="Screen Shot 2023-04-06 at 09 37 21" src="https://user-images.githubusercontent.com/104880745/230258390-2028334d-a83d-4d85-8e27-3d502faacdd9.png">
<img width="309" alt="Screen Shot 2023-04-06 at 09 37 39" src="https://user-images.githubusercontent.com/104880745/230258435-e524d96c-1906-46c1-b5de-3b993135cf35.png">

**Comment by bluesmoon** [comment]
Make sure your database is updated.

**Comment by linhnguyeneverfit** [comment]
@bluesmoon I don't get your point
Which db? I just simply test the lib

**Comment by linhnguyeneverfit** [comment]
Got it, I updated the database and it works.
Thanks a lot!
