### ISSUE TITLE
Error in getting the Info

### ISSUE THREAD

**Issue by starcelloo** [geoip-lite/node-geoip#260]
Hallo,
I have different results in using geoip-lite and Maxmind Demo site for a subset of IPs.
Checking in the CSV db it seems that Maxmind Demo gave correct results.

For example for IP
212.104.204.0 using the lookup I have "**nl**" as country
but in realty it have to be "**ca**"
In the CSV downloaded by the updatedb of the lib I have 
212.104.204.0/22,6251999,3017382,,0,0
where 6251999 is CANADA

Do you know what I'm missing?

**Comment by bluesmoon** [comment]
1. Are you using the latest version of the CSV database (downloaded from MaxMind)
2. Are you using the free version or the paid version of the CSV database?

The MaxMind demo website always uses the latest paid version, so you will have to use the same to get matching results.

**Comment by bluesmoon** [comment]
node-geoip:
```
node test/geo-lookup.js 212.104.204.0
{
  range: [ 3563637760, 3563638783 ],
  country: 'CA',
  region: 'QC',
  eu: '0',
  timezone: 'America/Toronto',
  city: 'Montreal',
  ll: [ 45.5457, -73.5805 ],
  metro: 0,
  area: 20
}
```

MaxMind:
<div id="result-table" class="sticky-table__wrapper" style="box-sizing: border-box; position: relative; margin-bottom: 15px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sticky-table__scroller result-table__table" style="box-sizing: border-box; max-height: 80vh; overflow-x: scroll; padding-bottom: 5px; width: 1296px; margin-bottom: 20px;">
IP Address | Country Code | Location | Network | Postal Code | Approximate Coordinates* | Accuracy Radius (km) | ISP | Organization | Domain | Metro Code
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
212.104.204.0 | CA | Montreal,Quebec,Canada,North America | 212.104.204.0/22 | H1Y | 45.5457,-73.5805 | 20 | UBISOFT Entertainment | UBISOFT Entertainment |   |  

</div></div><hr style="box-sizing: border-box; margin: 1.25rem 0px; color: rgb(33, 37, 41); border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(87, 102, 114); opacity: 0.25; height: 0px; font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="border bg-light" style="box-sizing: border-box; border: var(--bs-border-width) var(--bs-border-style) var(--bs-border-color) !important; --bs-bg-opacity: 1; background-color: rgba(var(--bs-light-rgb),var(--bs-bg-opacity)) !important; margin-bottom: 20px; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="card-body" style="box-sizing: border-box; flex: 1 1 auto; padding: 20px; color: var(--bs-card-color);"><br class="Apple-interchange-newline">
