### ISSUE TITLE
Seeking insight into the development process and buffer lookup approach used.

### ISSUE THREAD

**Issue by grundmanise** [geoip-lite/node-geoip#261]
Thank you for creating such a valuable package! The efficiency of its buffer lookup methods is particularly noteworthy. I'm curious whether the authors or anyone else has published any blog posts detailing the development process and how data CSV to Binary parsing/lookup was implemented. Understanding the workings of the package at a high level would be quite insightful. While I attempted to delve into the code, I found it challenging due to the scarcity of explanatory comments.

**Comment by bluesmoon** [comment]
It uses a simple binary search on an in-memory byte array with fixed width records: https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by grundmanise** [comment]
Thank you for your response. I appreciate your clarification. I'm especially interested in the specific heuristics employed for the bitwise encoding of CSV data and "aton" functions. I would be very grateful if you could point me towards any articles or resources that delve deeper into such bitwise operations that were used to parse CSV into byte array. Would like to expand my knowledge on this subject.
